### ISSUE TITLE
Добавить кликабельные ссылки

### ISSUE THREAD

**Issue by therealmonE** [therealmonE/fire-res#138]
Необходимо:

1) В меню "Помощь" добавить кликабельное меню "Руководство пользователя", которое открывает страницу с вики проекта
2) В модальное окно "О программе" добавить кликабельную ссылку на гит репозиторий

**Comment by therealmonE** [comment]
Открытие дефолтного браузера на ubuntu не работает. Решений пока нет

**Comment by therealmonE** [comment]
Затрачено: 1ч

**Comment by Jaxor1337** [comment]
Затрачено: 1ч
