### ISSUE TITLE
Страница отчета "Тепловой поток"

### ISSUE THREAD

**Issue by therealmonE** [therealmonE/fire-res#77]
Необходимо добавить в образцы страницу с отчетом "Тепловой поток", который включает в себя следующие инпуты:

1) Точки интерполяции (Продумать, см. задачу #67)
2) Коэффициент линейности - на подобие с #67 
3) Коэффициент дисперсии - на подобие с #67 
4) Количество сенсоров - spinner(integer), min - 1, max - 100, default - none
5) Макс. допустимый поток - spinner (integer), min - 1, max - 10000, default - none, increment - 100

**Comment by Jaxor1337** [comment]
Затрачено 8ч
