### ISSUE TITLE
Контекстное меню точек интерполяции

### ISSUE THREAD

**Issue by therealmonE** [therealmonE/fire-res#86]
Необходимо в таблицу точек интерполяции добавить контекстное меню с 1 опцией:

1) Добавить точку

https://stackoverflow.com/a/21012166

У каждой строки должно быть контекстное меню с 2мя опциями:

https://stackoverflow.com/a/31337761

1) Добавить точку
2) Удалить точку

**Comment by Jaxor1337** [comment]
Затрачено 5 часов
