### ISSUE TITLE
Вкладка отчета "Необогреваемая поверхность"

### ISSUE THREAD

**Issue by therealmonE** [therealmonE/fire-res#91]
Необходимо добавить в образцы вкладку "Необогреваемая поверхность", которая включает в себя:

1) Скрываемое окно "Первая группа термопар"
2) Скрываемое окно "Вторая группа термопар"
3) Скрываемое окно "Третья группа термопар"

Каждое окно включает в себя следующие группы параметров:

1) Параметры отчета:
    
    - Количество термопар: spinner(integer), min - 1, max - 100, default - 1
    
!!! Вторая и третья группа так же имеют следующий инпут:

    - Макс. допустимая температура: spinner(integer), min - 1, max - 10000, default - 300

2) Параметры функции (использовать готовый компонент)
3) График

**Comment by Jaxor1337** [comment]
Затрачено 10 часов
