### ISSUE TITLE
Интеграция гуи и генераторов (Режим пожара)

### ISSUE THREAD

**Issue by therealmonE** [therealmonE/fire-res#96]
На графике должны отображаться следующие линии:

1) Минимально допустимая температура (minAllowedTemperature)
2) Максимально допустимая температура (maxAllowedTemperature)
3) Стандартный режим пожара (standardTemperature) - линия должна быть пунктирная и не сильно выделяться
4) Среднее значение температуры в печи (meanThermocoupleTemperature)

Все изменения инпутов в "режиме пожара" должны сопровождаться вызовом нужного метода в FireModeService и обновлением графика

По возможности сделать линии на графике плавными

Для примера:
![image](https://user-images.githubusercontent.com/36332304/106887897-debf5080-66f6-11eb-9d86-7e73fb20f777.png)

**Comment by Jaxor1337** [comment]
Затрачено 5 часов

**Comment by therealmonE** [comment]
Затрачено: 2ч
